### ISSUE TITLE
Error in processing SIO

### ISSUE THREAD

**Issue by micheldumontier** [KnowledgeCaptureAndDiscovery/OBA#150]
Hi,
  I tried to use this with SIO (http://semanticscience.org/resource/sio.owl), but it fails with these messages

[main] WARN org.semanticweb.owlapi.util.SAXParsers - http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl, error message: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[main] WARN org.semanticweb.owlapi.util.SAXParsers - entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl, error message: Property 'entityExpansionLimit' is not recognized.
[main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.AbstractState - Notice: root element does not have an xml:base. Relative IRIs will be resolved against file:/C:/code/oba/outputs/sio/ontology0.owl
[main] INFO org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Unparsed triple: http://purl.org/dc/elements/1.1/identifier -> _:genid-nodeid-arc67d7b1023 -> ":arc67d7b1023"^^xsd:string

...
Exception in thread "main" java.lang.NullPointerException
        at edu.isi.oba.Mapper.add_owlclass_to_openapi(Mapper.java:157)
        at edu.isi.oba.Mapper.createSchemas(Mapper.java:128)
        at edu.isi.oba.Oba.main(Oba.java:69)

**Comment by dgarijo** [comment]
Hmm, this ontology is a little tricky. OBA may be confused because we usually expect the properties to be defined with proper domain and range, not using the "some" axiom. However, it should work, so I will look this up.
