### ISSUE TITLE
Java Error when Running jar-with-dependencies

### ISSUE THREAD

**Issue by michaelrowe01** [KnowledgeCaptureAndDiscovery/OBA#164]
I am trying to generate a OAS Schema based on a rdf/xml definition.  I am getting the following error when running the command line.
`target % java -jar oba-3.6.0-jar-with-dependencies.jar -c config.yaml 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
outputs/rqm-test/ontology0.owl
<http://jazz.net/ns/qm/rqm#Category>
<http://jazz.net/ns/qm/rqm#CategoryType>
<http://jazz.net/xmlns/prod/jazz/rqm/process/1.0/Priority>
<http://jazz.net/xmlns/prod/jazz/rqm/process/1.0/WorkflowState>
<http://open-services.net/ns/core#Property>
<http://open-services.net/ns/core#ResourceShape>
[2022-07-05 10:37:34] [SEVERE ] Error while creating the API specification: null 
java.lang.NullPointerException
	at edu.isi.oba.Mapper.add_owlclass_to_openapi(Mapper.java:156)
	at edu.isi.oba.Mapper.createSchemas(Mapper.java:126)
	at edu.isi.oba.Oba.main(Oba.java:71)`

I am attaching both the config.yaml and the qm.xml files in the attached ZIP file - [files.zip](https://github.com/KnowledgeCaptureAndDiscovery/OBA/files/9047272/files.zip)

**Comment by mosoriob** [comment]
The code couldn't contain the default prefix

```
format.asPrefixOWLDocumentFormat().getDefaultPrefix()
null
```

**Comment by dgarijo** [comment]
Thanks @mosoriob,
I have merged your PR addressing this issue. @michaelrowe01, you need to add a prefix for your ontology (at least a default one) so we know which is the main artifact on top of which we build the API.

**Comment by michaelrowe01** [comment]
Thanks @dgarijo Will update and confirm.

**Comment by michaelrowe01** [comment]
adding the additional "root" prefix worked...; however the output that was created in the yaml doesn't really provide what I was expecting..
[output.zip](https://github.com/KnowledgeCaptureAndDiscovery/OBA/files/9073908/output.zip)
there is no schema defined in the yaml

**Comment by dgarijo** [comment]
The output is indeed incorrect. 
However, from what I see in the `qm.xml` file, there are no owl:Classes. 
OBA expects OWL ontologies, and this one looks like it's defining its own terms for categories and properties. This is not supported at the moment (we support OWL/RDFs vocabularies)
