### ISSUE TITLE
Error while creating the API specification: Cannot invoke "String.equals(Object)" because "defaultOntologyPrefixIRI" is null

### ISSUE THREAD

**Issue by CFarcy** [KnowledgeCaptureAndDiscovery/OBA#170]
I am not sure if i done something wrong, but I tried to generate OAS, following the documentation. I tried first with your sample "config.yaml" provided in the doc. Works perfectly.

Then I tried with the dcat:Dataset ontology (https://www.w3.org/ns/dcat2.rdf) and the following error was raised:
```sh
[2022-11-16 17:19:46] [SEVERE ] Error while creating the API specification: Cannot invoke "String.equals(Object)" because "defaultOntologyPrefixIRI" is null 
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "defaultOntologyPrefixIRI" is null
        at edu.isi.oba.Mapper.add_owlclass_to_openapi(Mapper.java:156)
        at edu.isi.oba.Mapper.createSchemas(Mapper.java:126)
        at edu.isi.oba.Oba.main(Oba.java:71)
```

Here is the `config.yml` used :
```yml
ontologies:
  - https://www.w3.org/ns/dcat2.rdf 
name: dcat:dataset
output_dir: outputs

openapi:
  openapi: 3.0.1
  info:
    description: This is an API example for DCAT dataset 
    title: DCAT Dataset
    version: v1.0.0
  externalDocs:
    description: DCAT Dataset
    url: https://www.w3.org/ns/dcat#dataset
  servers:
    - url: http://localhost:8080/v1.0.0

endpoint:
  url: http://localhost:7200/sparql
  prefix: http://localhost:7200/resource
  graph_base: None
```
This error occurred with `oba-3.6.1-jar-with-dependencies.jar` on Pop!_os 22.04
```
 java --version
openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment (build 19.0.1+10-Ubuntu-1ubuntu122.04)
OpenJDK 64-Bit Server VM (build 19.0.1+10-Ubuntu-1ubuntu122.04, mixed mode, sharing)
```

**Comment by dgarijo** [comment]
Hmm, a default ontology URI is not found, but we have run OBA on these kind of ontologies before. I will have to dig in.

**Comment by CFarcy** [comment]
I think it was more a mistake on my side ( I am a bit new in the ontology world).
 
I make it work using the `classes` property in the config.yml file:

```yml
ontologies:
  - https://www.w3.org/ns/dcat2.rdf 
name: dcat
output_dir: outputs

classes:
 - https://www.w3.org/ns/dcat#Dataset

openapi:
  openapi: 3.0.1
  info:
    description: This is an API example for DCAT 
    title: DCAT
    version: v1.0.0
  externalDocs:
    description: DCAT
    url: https://www.w3.org/ns/dcat
  servers:
    - url: http://localhost:8080/v1.0.0

endpoint:
  url: http://localhost:7200/sparql
  prefix: http://localhost:7200/resource
  graph_base: None
```
I changed the name from `dcat:dataset` to `dcat` to match correctly with the ontology, then I used the `classes` property to run OBA only on `dcat#dataset`.

Now it works perfectly :tada:  !

**Comment by dgarijo** [comment]
Ok, then closing the issue. Thanks!
