### ISSUE TITLE
Running DBpedia_music server with Docker doesn't work

### ISSUE THREAD

**Issue by paoespinozarias** [KnowledgeCaptureAndDiscovery/OBA#73]
After building the server image, I tried to run it with Docket but I got the following error:  

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.8/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/openapi_server/__init__.py", line 4, in <module>
    query_manager = QueryManager(queries_dir=QUERY_DIRECTORY,
  File "/usr/local/lib/python3.8/site-packages/obasparql/query_manager.py", line 44, in __init__
    queries = self.read_template(queries_dir / owl_class)
  File "/usr/local/lib/python3.8/site-packages/obasparql/query_manager.py", line 190, in read_template
    for file_query in os.listdir(owl_class_dir):
NotADirectoryError: [Errno 20] Not a directory: '/usr/src/app/queries/.DS_Store'
`

Apparently, all the steps to generate the server were executed without a problem. I only got the following warnings/info when I run the OpenAPI generator script: 

`[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: python-flask (server)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'python-flask' is considered stable.
[main] INFO  o.o.c.l.PythonAbstractConnexionServerCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.l.PythonAbstractConnexionServerCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] WARN  o.o.codegen.DefaultCodegen - Empty operationId found for path: GET /bands. Renamed to auto-generated operationId: bandsGET
[main] WARN  o.o.codegen.DefaultCodegen - Empty operationId found for path: GET /bands/{id}. Renamed to auto-generated operationId: bandsIdGET
[main] WARN  o.o.codegen.DefaultCodegen - Empty operationId found for path: GET /genres. Renamed to auto-generated operationId: genresGET
[main] WARN  o.o.codegen.DefaultCodegen - Empty operationId found for path: GET /genres/{id}. Renamed to auto-generated operationId: genresIdGET` 

I have macOS with Python 3.7.5, Flask 1.1.2 and Docker 2.2.0.3.

**Comment by paoespinozarias** [comment]
With the new release, I was able to build the server image without any of the aforementioned problems. However, I was unable to run it because I got the following messages: 
`2020-04-27 09:37:51,770 - openapi_server.cached - WARNING - Cache file does not exist: [Errno 2] No such file or directory: '/usr/src/app/openapi_server/openapi/openapi.yaml.cache'`

` File "/usr/src/app/openapi_server/utils/vars.py", line 1243
    <HTTP://DBPEDIA.ORG/ONTOLOGY/>_TYPE_URI = "http://dbpedia.org/ontology/"
    ^
SyntaxError: invalid syntax`

(I have omitted the full traceback and included only the specific lines)

**Comment by sirspock** [comment]
You can ignore the warning (I'm going to improve the message)
```
 2020-04-27 09:37:51,770 - openapi_server.cached - WARNING - Cache file does not exist: [Errno 2] No such file or directory: '/usr/src/app/openapi_server/openapi/openapi.yaml.cache'
```

**Comment by sirspock** [comment]
DBPedia has a weird class `HTTP://DBPEDIA.ORG/ONTOLOGY`
I'm going to ignore the class without a name.

```
File "/usr/src/app/openapi_server/utils/vars.py", line 1243 <HTTP://DBPEDIA.ORG/ONTOLOGY/>_TYPE_URI = "http://dbpedia.org/ontology/" ^ SyntaxError: invalid synt
```

**Comment by sirspock** [comment]
Fixed in the v3.1.0
```
[2020-04-27 15:44:48] [WARNING] Ignoring class http://dbpedia.org/ontology/
[2020-04-27 15:44:48] [WARNING] Ignoring class http://dbpedia.org/ontology/
[2020-04-27 15:44:54] [WARNING] Generating of context.json - Ignoring the class {"@id":"http://dbpedia.org/ontology/"}: Name is empty.
[2020-04-27 15:44:54] [WARNING] Generating of context.json - Ignoring the class {"@id":"http://dbpedia.org/ontology/"}: Name is empty.
```

**Comment by paoespinozarias** [comment]
Thanks!  The server properly runs with this new release v3.1.0.

**Comment by dgarijo** [comment]
Where you able to also query the resources fine?
