### ISSUE TITLE
Error processing ontology network

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/OBA#79]
@varunratnakar tested OBA with the following configuration:
```
ontologies:
  - http://www.wings-workflows.org/ontology/workflow.owl
  - http://www.wings-workflows.org/ontology/data.owl
  - http://www.wings-workflows.org/ontology/component.owl
name: wings
output_dir: outputs

openapi:
  openapi: 3.0.1
  info:
    description: This is the API of the Wings Ontology
    title: Wings Workflow Catalog
    version: v1.4.0
  externalDocs:
    description: Wings Workflow Catalog
    url: https://w3id.org/okn/o/sdm
  servers:
    - url: http://localhost:8080

firebase:
  key:

endpoint:
  url: http://localhost:3030/wings
  prefix: http://www.wings-workflows.org/ontology
  graph_base: http://localhost:3030/wings/data/
```
And he got the following error:
```
I get this :
java.io.IOException: owljson failed
at edu.isi.oba.ObaUtils.run_owl_jsonld(ObaUtils.java:222)
at edu.isi.oba.ObaUtils.generate_context_file(ObaUtils.java:205)
at edu.isi.oba.Oba.generate_context(Oba.java:87)
at edu.isi.oba.Oba.main(Oba.java:81)
java.io.IOException: owljson failed
at edu.isi.oba.ObaUtils.run_owl_jsonld(ObaUtils.java:222)
at edu.isi.oba.ObaUtils.generate_context_file(ObaUtils.java:205)
at edu.isi.oba.Oba.generate_context(Oba.java:87)
at edu.isi.oba.Oba.main(Oba.java:81)
java.io.IOException: owljson failed
at edu.isi.oba.ObaUtils.run_owl_jsonld(ObaUtils.java:222)
at edu.isi.oba.ObaUtils.generate_context_file(ObaUtils.java:205)
at edu.isi.oba.Oba.generate_context(Oba.java:87)
at edu.isi.oba.Oba.main(Oba.java:81)
Exception in thread "main" java.lang.NullPointerException
at edu.isi.oba.ObaUtils.concat_json_common_key(ObaUtils.java:169)
at edu.isi.oba.ObaUtils.generate_context_file(ObaUtils.java:212)
at edu.isi.oba.Oba.generate_context(Oba.java:87)
at edu.isi.oba.Oba.main(Oba.java:81)
```
It looks like a problem with the context generation...

**Comment by sirspock** [comment]
Fixed in the 3.0.0 release
https://github.com/KnowledgeCaptureAndDiscovery/OBA/releases/tag/3.0.0
